# Generated by Django 5.2.8 on 2025-11-10 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BirthChart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sun_sign", models.CharField(blank=True, max_length=20, null=True)),
                ("moon_sign", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "ascendant_sign",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("sun_position", models.FloatField(blank=True, null=True)),
                ("moon_position", models.FloatField(blank=True, null=True)),
                ("ascendant_position", models.FloatField(blank=True, null=True)),
                ("leadership", models.FloatField(default=0)),
                ("courage", models.FloatField(default=0)),
                ("charisma", models.FloatField(default=0)),
                ("sensitivity", models.FloatField(default=0)),
                ("intelligence", models.FloatField(default=0)),
                ("sun_description", models.TextField(blank=True, null=True)),
                ("moon_description", models.TextField(blank=True, null=True)),
                ("ascendant_description", models.TextField(blank=True, null=True)),
                ("daily_prediction", models.TextField(blank=True, null=True)),
                ("weekly_prediction", models.TextField(blank=True, null=True)),
                ("monthly_prediction", models.TextField(blank=True, null=True)),
                ("love_reading", models.TextField(blank=True, null=True)),
                ("career_reading", models.TextField(blank=True, null=True)),
                ("money_reading", models.TextField(blank=True, null=True)),
                ("health_reading", models.TextField(blank=True, null=True)),
                ("chinese_astrology", models.TextField(blank=True, null=True)),
                ("tarot_reading", models.TextField(blank=True, null=True)),
                ("numerology_reading", models.TextField(blank=True, null=True)),
                ("planets_reading", models.TextField(blank=True, null=True)),
                ("compatibility_reading", models.TextField(blank=True, null=True)),
                ("psychic_reading", models.TextField(blank=True, null=True)),
                ("calculated_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="birth_chart",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("monthly", "Mensal - R$ 19,99"),
                            ("semester", "Semestral - R$ 13,99/mês"),
                            ("annual", "Anual - R$ 11,99/mês"),
                            ("free", "Gratuito"),
                        ],
                        default="free",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Ativa"),
                            ("expired", "Expirada"),
                            ("cancelled", "Cancelada"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField(auto_now_add=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Masculino"), ("F", "Feminino"), ("O", "Outro")],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("birth_time", models.TimeField(blank=True, null=True)),
                ("birth_city", models.CharField(blank=True, max_length=200, null=True)),
                ("birth_latitude", models.FloatField(blank=True, null=True)),
                ("birth_longitude", models.FloatField(blank=True, null=True)),
                (
                    "birth_timezone",
                    models.CharField(default="America/Sao_Paulo", max_length=100),
                ),
                (
                    "current_feeling",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("feliz", "Feliz"),
                            ("ansioso", "Ansioso"),
                            ("estressado", "Estressado"),
                            ("motivado", "Motivado"),
                            ("outro", "Outro"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "current_objective",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("paixao", "Paixão"),
                            ("dinheiro", "Dinheiro"),
                            ("saude", "Saúde"),
                            ("autoconhecimento", "Autoconhecimento"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("quiz_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
